//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulesPR5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgencyStaff
    {
        public int id { get; set; }
        public string full_name { get; set; }
        public string position { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public Nullable<int> auth_id { get; set; }
    
        public virtual Auth Auth { get; set; }
    }
}
