//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulesPR5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantStatus
    {
        public ApplicantStatus()
        {
            this.Applicants = new HashSet<Applicants>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Applicants> Applicants { get; set; }
    }
}
