//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulesPR5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicants
    {
        public Applicants()
        {
            this.Chats = new HashSet<Chats>();
            this.Messages = new HashSet<Messages>();
            this.Placements = new HashSet<Placements>();
            this.Resumes = new HashSet<Resumes>();
        }
    
        public int id { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public System.DateTime birth_date { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public int status_id { get; set; }
        public Nullable<int> auth_id { get; set; }
    
        public virtual ApplicantStatus ApplicantStatus { get; set; }
        public virtual ICollection<Chats> Chats { get; set; }
        public virtual ICollection<Messages> Messages { get; set; }
        public virtual ICollection<Placements> Placements { get; set; }
        public virtual ICollection<Resumes> Resumes { get; set; }
        public virtual Auth Auth { get; set; }
    }
}
