//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulesPR5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auth
    {
        public Auth()
        {
            this.Applicants = new HashSet<Applicants>();
            this.Companies = new HashSet<Companies>();
        }
    
        public int id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int role_id { get; set; }
    
        public virtual ICollection<Applicants> Applicants { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual ICollection<Companies> Companies { get; set; }
    }
}
