//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulesPR5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chats
    {
        public Chats()
        {
            this.Messages = new HashSet<Messages>();
        }
    
        public int id { get; set; }
        public int applicant_id { get; set; }
        public int company_id { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual Applicants Applicants { get; set; }
        public virtual Companies Companies { get; set; }
        public virtual ICollection<Messages> Messages { get; set; }
    }
}
