//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulesPR5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Companies
    {
        public Companies()
        {
            this.Chats = new HashSet<Chats>();
            this.Messages = new HashSet<Messages>();
            this.Vacancies = new HashSet<Vacancies>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string inn { get; set; }
        public string address { get; set; }
        public string contact_person { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public Nullable<int> auth_id { get; set; }
    
        public virtual Auth Auth { get; set; }
        public virtual ICollection<Chats> Chats { get; set; }
        public virtual ICollection<Messages> Messages { get; set; }
        public virtual ICollection<Vacancies> Vacancies { get; set; }
    }
}
