//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulesPR5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        public int id { get; set; }
        public int doc_type_id { get; set; }
        public int related_id { get; set; }
        public System.DateTime created_at { get; set; }
        public string content { get; set; }
    
        public virtual DocumentTypes DocumentTypes { get; set; }
    }
}
