//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulesPR5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int id { get; set; }
        public int chat_id { get; set; }
        public Nullable<int> sender_applicant_id { get; set; }
        public Nullable<int> sender_company_id { get; set; }
        public string message_text { get; set; }
        public System.DateTime sent_at { get; set; }
    
        public virtual Applicants Applicants { get; set; }
        public virtual Chats Chats { get; set; }
        public virtual Companies Companies { get; set; }
    }
}
