//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulesPR5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cadrAgEntities : DbContext
    {
        public cadrAgEntities()
            : base("name=cadrAgEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AgencyStaff> AgencyStaff { get; set; }
        public DbSet<Applicants> Applicants { get; set; }
        public DbSet<ApplicantStatus> ApplicantStatus { get; set; }
        public DbSet<Auth> Auth { get; set; }
        public DbSet<Chats> Chats { get; set; }
        public DbSet<Companies> Companies { get; set; }
        public DbSet<Documents> Documents { get; set; }
        public DbSet<DocumentTypes> DocumentTypes { get; set; }
        public DbSet<Messages> Messages { get; set; }
        public DbSet<Placements> Placements { get; set; }
        public DbSet<Responses> Responses { get; set; }
        public DbSet<ResponseStatus> ResponseStatus { get; set; }
        public DbSet<Resumes> Resumes { get; set; }
        public DbSet<Statistic> Statistic { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Vacancies> Vacancies { get; set; }
        public DbSet<VacancyStatus> VacancyStatus { get; set; }
    }
}
