//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulesPR5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Responses
    {
        public int id { get; set; }
        public int resume_id { get; set; }
        public int vacancy_id { get; set; }
        public System.DateTime responded_at { get; set; }
        public int status_id { get; set; }
    
        public virtual Resumes Resumes { get; set; }
        public virtual ResponseStatus ResponseStatus { get; set; }
        public virtual Vacancies Vacancies { get; set; }
    }
}
