//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulesPR5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resumes
    {
        public Resumes()
        {
            this.Responses = new HashSet<Responses>();
        }
    
        public int id { get; set; }
        public int applicant_id { get; set; }
        public System.DateTime created_at { get; set; }
        public string description { get; set; }
        public string skills { get; set; }
        public string education { get; set; }
        public string work_experience { get; set; }
    
        public virtual Applicants Applicants { get; set; }
        public virtual ICollection<Responses> Responses { get; set; }
    }
}
