//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulesPR5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistic
    {
        public int id { get; set; }
        public string period { get; set; }
        public int hired_count { get; set; }
        public int response_count { get; set; }
        public int vacancy_count { get; set; }
    }
}
