//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulesPR5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacancies
    {
        public Vacancies()
        {
            this.Placements = new HashSet<Placements>();
            this.Responses = new HashSet<Responses>();
        }
    
        public int id { get; set; }
        public int company_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string requirements { get; set; }
        public decimal salary { get; set; }
        public int status_id { get; set; }
    
        public virtual Companies Companies { get; set; }
        public virtual ICollection<Placements> Placements { get; set; }
        public virtual ICollection<Responses> Responses { get; set; }
        public virtual VacancyStatus VacancyStatus { get; set; }
    }
}
